language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools

  # The BuildTools version used by your project
  - build-tools-28.0.3
  - build-tools-26.0.3
  - build-tools-22.0.3

  # The SDK version used to compile your project
  - android-22
  - android-26
  - android-26

  # Support library
  - extra-android-support
  - extra-android-m2repository

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  - sys-img-armeabi-v7a-android-22
  - sys-img-armeabi-v7a-android-26
  - sys-img-armeabi-v7a-android-28
before_install:
- yes | sdkmanager "platforms;android-28"
- chmod +x gradlew
script:
- ./gradlew jacocoTestReport coveralls
- ./gradlew assembleRelease --stacktrace